//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtSolution.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kraka.ucn.dk;Initial Catalog=dmab0913_4sem_gruppe5;Persist Security I" +
            "nfo=True;User ID=dmab0913_4sem_gruppe5;Password=Biksemad")]
        public string dmab0913_4sem_gruppe5ConnectionString {
            get {
                return ((string)(this["dmab0913_4sem_gruppe5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kraka.ucn.dk;Persist Security Info=True;User ID=dmab0913_4sem_gruppe5" +
            ";Password=Biksemad")]
        public string DataSourceConnectionString {
            get {
                return ((string)(this["DataSourceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Kraka.UCn.dk;Initial Catalog=dmab0913_4sem_gruppe5;Persist Security I" +
            "nfo=True;User ID=dmab0913_4sem_gruppe5;Password=Biksemad")]
        public string dmab0913_4sem_gruppe5ConnectionString2 {
            get {
                return ((string)(this["dmab0913_4sem_gruppe5ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kraka.ucn.dk;Initial Catalog=dmab0913_4sem_gruppe5;Persist Security I" +
            "nfo=True;User ID=dmab0913_4sem_gruppe5;Password=Biksemad")]
        public string dmab0913_4sem_gruppe5ConnectionString1 {
            get {
                return ((string)(this["dmab0913_4sem_gruppe5ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=j81655ta16.database.windows.net;Initial Catalog=\"Technical Yacht Solu" +
            "tions\";Persist Security Info=True;User ID=TYS;Password=Rasmus1234")]
        public string Technical_Yacht_SolutionsConnectionString {
            get {
                return ((string)(this["Technical_Yacht_SolutionsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Kraka.ucn.dk;Initial Catalog=dmab0913_4sem_gruppe4;User ID=dmab0913_4" +
            "sem_gruppe4;Password=Biksemad")]
        public string dmab0913_4sem_gruppe4ConnectionString {
            get {
                return ((string)(this["dmab0913_4sem_gruppe4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tys.database.windows.net;Initial Catalog=\"Technical Yacht Solution\";P" +
            "ersist Security Info=True;User ID=Rasmus;Password=Technical15")]
        public string Technical_Yacht_SolutionConnectionString {
            get {
                return ((string)(this["Technical_Yacht_SolutionConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\Test;Initial Catalog=\"Technical Yacht Solutions\";Integrated" +
            " Security=True")]
        public string Technical_Yacht_SolutionsConnectionString1 {
            get {
                return ((string)(this["Technical_Yacht_SolutionsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tys.database.windows.net;Initial Catalog=\"Technical Yacht Solution\";U" +
            "ser ID=Rasmus;Password=Technical15")]
        public string Technical_Yacht_SolutionConnectionString1 {
            get {
                return ((string)(this["Technical_Yacht_SolutionConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=\"|DataDirectory|\\Technical Yacht So" +
            "lutions.accdb\"")]
        public string Technical_Yacht_SolutionsConnectionString2 {
            get {
                return ((string)(this["Technical_Yacht_SolutionsConnectionString2"]));
            }
        }
    }
}
